### PR TITLE
git-annex: enable /media/ links

### LINKED ISSUE #19: HTTP downloads fail without '.git'
```
git clone https://domain.tld/user/repo.git
cd repo
git annex get
```

works, but

```
git clone https://domain.tld/user/repo/
cd repo
git annex get
```

fails.

<details><summary>logs</summary>
```
p115628@joplin:~/datasets$ time git clone https://data.dev.neuropoly.org/nick.guenther/spine-generic-single/ data-single-subject-http
Clonage dans 'data-single-subject-http'...
remote: Enumerating objects: 3243, done.
remote: Counting objects: 100% (3243/3243), done.
remote: Compressing objects: 100% (1228/1228), done.
remote: Total 3243 (delta 1614), reused 2595 (delta 1260), pack-reused 0
Réception d'objets: 100% (3243/3243), 311.17 Kio | 8.89 Mio/s, fait.
Résolution des deltas: 100% (1614/1614), fait.

real    0m0,339s
user    0m0,147s
sys     0m0,119s
p115628@joplin:~/datasets$ cd data-single-subject-http
p115628@joplin:~/datasets/data-single-subject-http$ git config annex.debug true
p115628@joplin:~/datasets/data-single-subject-http$ git annex init
init  [2022-09-22 21:05:53.958616271] process [784927] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2022-09-22 21:05:53.960566819] process [784927] done ExitSuccess
[2022-09-22 21:05:53.963044269] process [784928] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","git-annex"]
[2022-09-22 21:05:53.965184902] process [784928] done ExitSuccess
[2022-09-22 21:05:53.965650222] process [784929] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2022-09-22 21:05:53.967675943] process [784929] done ExitSuccess
[2022-09-22 21:05:53.968580648] process [784930] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","log","refs/heads/git-annex..fe8e6a4bb0b399c469f9e324ac9d2edfbd0a4e46","--pretty=%H","-n1"]
[2022-09-22 21:05:53.971604225] process [784930] done ExitSuccess
[2022-09-22 21:05:53.972627993] process [784931] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch"]
[2022-09-22 21:05:53.973282531] process [784932] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
[2022-09-22 21:05:53.9745717] process [784933] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","status","--porcelain"]
[2022-09-22 21:05:53.979748867] process [784933] done ExitSuccess
[2022-09-22 21:05:53.980242194] process [784934] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","filter.annex.smudge","git-annex smudge -- %f"]
[2022-09-22 21:05:53.981837575] process [784934] done ExitSuccess
[2022-09-22 21:05:53.982277596] process [784935] read: git ["config","--null","--list"]
[2022-09-22 21:05:53.992094121] process [784935] done ExitSuccess
[2022-09-22 21:05:53.992458675] process [784936] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","filter.annex.clean","git-annex smudge --clean -- %f"]
[2022-09-22 21:05:53.994267592] process [784936] done ExitSuccess
[2022-09-22 21:05:53.994750671] process [784937] read: git ["config","--null","--list"]
[2022-09-22 21:05:53.997007977] process [784937] done ExitSuccess
(scanning for unlocked files...)
[2022-09-22 21:05:53.997436618] process [784938] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--head"]
[2022-09-22 21:05:53.999476284] process [784938] done ExitSuccess
[2022-09-22 21:05:53.999963275] process [784939] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","ls-tree","--full-tree","-z","-r","--","HEAD"]
[2022-09-22 21:05:54.00211884] process [784940] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch"]
[2022-09-22 21:05:54.002558673] process [784941] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
[2022-09-22 21:05:54.069418088] process [784939] done ExitSuccess
[2022-09-22 21:05:54.069785424] process [784943] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","symbolic-ref","-q","HEAD"]
[2022-09-22 21:05:54.07159061] process [784943] done ExitSuccess
[2022-09-22 21:05:54.071961591] process [784944] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","refs/heads/master"]
[2022-09-22 21:05:54.074562387] process [784944] done ExitSuccess
[2022-09-22 21:05:54.074847453] process [784945] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","symbolic-ref","-q","HEAD"]
[2022-09-22 21:05:54.076504425] process [784945] done ExitSuccess
[2022-09-22 21:05:54.076975747] process [784946] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/master"]
[2022-09-22 21:05:54.07950515] process [784946] done ExitSuccess
[2022-09-22 21:05:54.07994172] process [784947] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","checkout","-q","-B","master"]
[2022-09-22 21:05:54.104185386] process [784947] done ExitSuccess
[2022-09-22 21:05:54.123333435] Request {
  host                 = "data.dev.neuropoly.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding","identity"),("User-Agent","git-annex/8.20210223")]
  path                 = "/nick.guenther/spine-generic-single//config"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}


  Remote origin not usable by git-annex; setting annex-ignore
[2022-09-22 21:05:54.270433893] process [784956] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","config","remote.origin.annex-ignore","true"]
[2022-09-22 21:05:54.273061661] process [784956] done ExitSuccess
[2022-09-22 21:05:54.273579089] process [784957] read: git ["config","--null","--list"]
[2022-09-22 21:05:54.275885507] process [784957] done ExitSuccess
ok
[2022-09-22 21:05:54.290599771] process [784940] done ExitSuccess
[2022-09-22 21:05:54.291246091] process [784941] done ExitSuccess
[2022-09-22 21:05:54.291774635] process [784931] done ExitSuccess
[2022-09-22 21:05:54.292512343] process [784932] done ExitSuccess
```

</details>

### PR DESCRIPTION
**Pull request by kousu**
Previously, Gitea's LFS support allowed direct-downloads of LFS content, via http://$HOSTNAME:$PORT/$USER/$REPO/media/branch/$BRANCH/$FILE This expands that grace to git-annex too.

~~This also includes corresponding UI changes, mostly to the output of view_file.tmpl.~~ moved to #22

### CODE REVIEW

**Comment by kousu** [comment]
This will be needed for [my plan to](https://github.com/neuropoly/computers/issues/167#issuecomment-1272611388) integrate [Cornerstone](https://www.cornerstonejs.org/) into Neurogitea.

**Comment by kousu** [comment]
TODO:

* [ ] Add a case for git-annex to

    https://github.com/neuropoly/gitea/blob/b999fb810350b503f180d4516b0385696ea0514f/templates/repo/view_file.tmpl#L27-L29
* [ ] Rearrange

     https://github.com/neuropoly/gitea/blob/b999fb810350b503f180d4516b0385696ea0514f/routers/web/repo/view.go#L429

     so that

     https://github.com/neuropoly/gitea/blob/b999fb810350b503f180d4516b0385696ea0514f/templates/repo/view_file.tmpl#L102-L104

    outputs '/media' in both the git-annex and git-lfs cases.
* [ ] Add downloading via /media to the tests

**Comment by kousu** [comment]
I've gotten the view template to render annex files:

Screenshot 2022-11-07 at 18-37-44 lfs-test

and made the "View Raw File" link there link to a path like http://HOSTNAME/$USER/$REPO/media/branch/main/sub-glen_acq-T1w_MTS.nii.gz.

I also made sure it can render text files; notice this is "Stored with git-annex" but still renders inline:

Screenshot 2022-11-07 at 18-39-18 lfs-test

I haven't tested.

I've also noticed another TODO I didn't handle yet: symlink-based annex files render as symlinks (obviously) and aren't detected as annex pointers:

Screenshot 2022-11-07 at 18-40-00 lfs-test

* [ ] Patch annex.ReadPointer to handle symlinks; probably means adding a os.ReadLink() call

**Comment by kousu** [comment]
Also, there's a way to test the templates, which might be useful; here's an example:

https://github.com/neuropoly/gitea/blob/0afe11d4b436163e8dcf6d5d54a22707d6d18563/tests/integration/repo_test.go#L22-L37

which seems to be based on https://pkg.go.dev/github.com/PuerkitoBio/goquery.

in particular, I want to test for:

- [ ] view_file.tmpl renders "/media" and not "/raw" when used on annexed files
- [ ] the index page *does not* render the symlink icon on a file that's an *annex* symlink

File: modules/annex/annex.go [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+	// ask git-annex's opinion on $KEY
+	// XXX: this is probably a bit slow, especially if this operation gets run often
+	//      and examinekey is not that strict:
+	//      - it doesn't enforce that the "BACKEND" tag is one it knows,
+	//      - it doesn't enforce that the fields and their format fit the "BACKEND" tag
+	//      so maybe this is a wasteful step
+	_, examineStderr, err := git.NewCommandNoGlobals("annex", "examinekey", git.CmdArg(pointer)).RunStdString(&git.RunOpts{Dir: repoPath})
+	if err != nil {
+		// TODO: make ErrInvalidPointer into a type capable of wrapping err
+		if strings.TrimSpace(examineStderr) == "git-annex: bad key" {
```
Comment (kousu) [inline modules/annex/annex.go:101]: Worry: is git-annex locale-sensitive? What happens if it outputs "git-annex: mauvais clé"?

File: modules/annex/annex.go [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+		return "", err
+	}
+	defer dataRc.Close()
+	buf := make([]byte, n)
+	n, _ = util.ReadAtMost(dataRc, buf)
+	buf = buf[:n]
+	return string(buf), nil
+}
+
+func Pointer(repoPath string, blob *git.Blob) (string, error) {
```
Comment (kousu) [inline modules/annex/annex.go:45]: Can I get `repoPath` out of `git.Blob`? Looks like maybe? `blob.repo.Path == repoPath` (if compiling *without* `TAGS=gogit`).

File: modules/annex/annex.go [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+			return "", ErrInvalidPointer
+		}
+		return "", err
+	}
+
+	return pointer, nil
+}
+
+// returns the relative storage path of the pointer
+func ContentLocation(repoPath string, blob *git.Blob) (string, error) {
```
Comment (kousu) [inline modules/annex/annex.go:111]: This function is now redundant with `annexObjectPath` in tests/integration/git_annex_test.go.

But their APIs are subtly and difficultly different. So it'll be some work to cut one of them.

File: modules/git/tree_entry.go [hunk 4]
```diff
@@ -11,6 +11,10 @@ import (
 	"strings"
 )
 
+func (te *TreeEntry) Repo() *Repository {
+	return te.ptree.repo
+}
```
Comment (kousu) [inline modules/git/tree_entry.go:16]: Annoyingly necessary to punch through the package-private variables here due to the lines in the previous file..

File: options/locale/locale_cs-CZ.ini [hunk 5]
```diff
@@ -1067,6 +1067,7 @@ view_git_blame=Zobrazit Git Blame
 video_not_supported_in_browser=Váš prohlížeč nepodporuje značku pro HTML5 video.
 audio_not_supported_in_browser=Váš prohlížeč nepodporuje značku pro HTML5 audio.
 stored_lfs=Uloženo pomocí Git LFS
+stored_annex=Uloženo pomocí Git Annex
```
Comment (kousu) [inline options/locale/locale_cs-CZ.ini:1070]: I did all of these by manually copy-pasting the `stored_lfs` lines.

**Comment by kousu** [comment]
TODO:

- [ ] The very first commit is failing the tests with

    > exit status 128 - fatal: working tree '/home/GRAMES.POLYMTL.CA/p115628/src/neurogitea/gitea' already exists.

    but the *other* commits are passing. So I've messed something up during my rebasing.
- [ ] split up into three PRs:
    1. modules/annex/
    2. /media links + tests
    3. views + tests
